# base image
FROM node:12-alpine

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

# install and cache app dependencies
COPY package.json /app/package.json
RUN npm install
RUN npm install -g @angular/cli@7.3.9

# add app
COPY . /app

EXPOSE 80
# start app
CMD ng serve --configuration=production -- --host=0.0.0.0 --disable-host-check --port=80 --proxy-config proxy.conf-prod.js --base-href /